### ISSUE TITLE
editable fields

### ISSUE THREAD

**Issue by ksmth** [Lapple/react-json-inspector#3]
hey, thanks for developing the component :)

my app needs to to display, search and _modify_ json object. do you have anything planned for this? if not, would you accept a proper pull request including such a feature?

**Comment by Lapple** [comment]
Hello, there is already something in place that might help you: each key and primitive property renders a hidden input that could become visible once that block is focused – much like it's done in Chrome DevTools:

![Editable fields](http://i.imgur.com/KrOMj5v.png)

To enable that, add the following to your CSS:

``` css
.json-inspector__selection {
    display: block;
    position: absolute;
    top: 0;
    left: -3px;
    right: 0;
    z-index: 1;
    padding: 0 3px;

    font: 11px/1 Menlo, Consolas, monospace;
    outline: none;
    border: none;
    opacity: 0;
    box-shadow: 3px 3px 4px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(0, 0, 0, 0.3);
    color: #222;
}

.json-inspector__selection:focus {
    opacity: 1;
}
```

The component is located in `lib/selection.js`, for now it's a readonly input. I believe, it could be extended to handle modification (i.e. save on Enter, discard on blur). On the other hand, we could allow for this sort of extended functionality to be passed as an option to the whole inspector component – much like it's already done for [`searchBar` component](https://github.com/Lapple/react-json-inspector#propssearch). What do you think?
